baseURL       = "https://interviewvector.com/"
languageCode  = "en-us"
title         = "InterviewVector"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  #[[menu.nav]]
  #  name    = "About"
  #  url     = "about"
  #  weight  = 2
  [[menu.nav]]
    name    = "Services"
    url     = "#service"
    weight  = 3
  [[menu.nav]]
    name    = "Get in touch"
    url     = "#contact"
    weight  = 4

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "13 JUN 2020"
  # Meta data
  description = "InterviewVector | Giving Directions to your interviews"
  author = "InterviewVector"
  # Google Analitycs
  googleAnalitycsID = "UA-169346276-1"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "#contact"


  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "We provide Interview as a service"
    tagline               = "Giving Directions to your Interviews"
    enable_buttons        = false
    #primary_button        = "See Our Services"
    #primary_button_url    = "#service"
    #secondary_button      = "Connect with Us"
    #secondary_button_url  = "#contact"

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "#contact"
    #secondary_button    = "Not Convinced"
    #secondary_button_url = "#service"

  [params.contact]
    enable       = true
    heading      = "Don’t be shy. Say <span>Hello.</span>"
    form_heading = "Drop Us A Note"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = ""
      phone   = "+91 97068 70735"
      email   = "contact@interviewvector.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        #[[params.footer.sitemap.link]]
        #  name = "About Company"
        #  url  = "#about"
        [[params.footer.sitemap.link]]
          name = "Services"
          url  = "#service"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "#contact"
      # Footer Social Media
      [params.footer.social]
        enable  = false
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      #[params.footer.service]
      #  title       = "We help brands:"
      #  description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
